stages:
  - test
  - build

latexmk:
  image: tianon/latex:latest
  stage: build
  tags:
    - latex
  artifacts:
    paths:
      - main.pdf
    expire_in: 2d
  script:
    - latexmk main.tex

hunspell:
  image: tmaier/hunspell:latest
  stage: test
  tags:
    - hunspell
  script:
    - export HUNSPELL_FINDINGS=`for filename in chapter/*.tex; do hunspell -l -d de_DE_frami,en_US -p ./.hunspellignore -t $filename; done | sort | uniq`
    - echo $HUNSPELL_FINDINGS
    - test "$HUNSPELL_FINDINGS" == ""
  allow_failure: true