stages:
  - test
  - build

latexmk:
  image: bnord01/docker-latex-pygments:latest
  stage: build
  artifacts:
    paths:
      - main*.pdf
    expire_in: 2d
  script:
    - latexmk main.tex
    - ci_commit_sha_short=`git rev-parse --short $CI_COMMIT_SHA`
    - mv main.pdf main@$ci_commit_sha_short.pdf


hunspell:
  image: tmaier/hunspell:latest
  stage: test
  script:
    - export HUNSPELL_FINDINGS=`for filename in chapter/*.tex; do hunspell -l -d de_DE_neu,en_US -p ./.hunspellignore -t $filename; done | sort | uniq`
    - echo $HUNSPELL_FINDINGS
    - test "$HUNSPELL_FINDINGS" == ""
  allow_failure: true